# name: Jack

# on: workflow_run

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     env: 
#       PUBLIC_URL: https://iamlars.nl/seedle
#       GENERATE_SOURCEMAP: false
#     steps:
#       - name: ðŸšš Get latest code
#         uses: actions/checkout@v4.2.2

#       - name: ðŸ“¦ Install dependencies
#         uses: Borales/actions-yarn@v5.0.0
#         with:
#           cmd: install --production

#       - name: ðŸ”¨ Build Project
#         uses: borales/actions-yarn@v5.0.0
#         with:
#           cmd: build

#       - name: ðŸ“‚ Sync files
#         uses: SamKirkland/FTP-Deploy-Action@4.3.3
#         with:
#           server: ${{ secrets.FTP_SERVER }}
#           port: 21
#           username: ${{ secrets.FTP_USERNAME }}
#           password: ${{ secrets.FTP_PASSWORD }}
#           local-dir: ./dist/
#           server-dir: www/seedle/
#           state-name: ../.ftp-deploy-sync-state.json
